import type { TutorialStep } from '@/types/tutorial';

export const supportTutorialSteps = [
  {
    id: 'choose-request-type',
    shortTitle: 'Escolher',
    title: 'Escolha o tipo de atendimento',
    description: 'Escolha o caminho que corresponde ao que você precisa.',
    captures: [
      {
        id: 'home-request-options',
        title: 'Na página inicial',
        description: 'Use uma das duas opções destacadas.',
        src: '/portal/inicio.png',
        width: 1300,
        height: 350,
        hotspots: [
          {
            id: 1,
            x: 35,
            y: 22,
            width: 31,
            height: 30,
            label: 'Reportar um problema',
            description: 'Use quando algo que funcionava apresentou falha.',
            evidence: 'observed',
          },
          {
            id: 2,
            x: 68,
            y: 22,
            width: 31,
            height: 30,
            label: 'Solicitar um serviço',
            description: 'Use para pedir instalação, criação ou alteração.',
            evidence: 'observed',
          },
        ],
      },
    ],
  },
  {
    id: 'set-urgency-and-category',
    shortTitle: 'Classificar',
    title: 'Defina urgência e categoria',
    description: 'Classifique o impacto e o assunto do chamado.',
    captures: [
      {
        id: 'urgency-options',
        title: 'Urgência',
        description: 'Escolha um dos cinco níveis disponíveis.',
        src: '/portal/urgencia-completa.png',
        width: 460,
        height: 260,
        hotspots: [
          {
            id: 1,
            x: 4.1,
            y: 16.5,
            width: 91.3,
            height: 14,
            label: 'Abrir Urgência',
            description: 'Clique no campo para ver a lista.',
            evidence: 'observed',
          },
          {
            id: 2,
            x: 4.1,
            y: 30.8,
            width: 91.3,
            height: 67.3,
            label: 'Escolher a urgência',
            description: 'Selecione um dos cinco níveis exibidos.',
            evidence: 'observed',
          },
        ],
      },
      {
        id: 'category-options',
        title: 'Categoria',
        description: 'Escolha a opção mais específica para o caso.',
        src: '/portal/categoria-selecao.png',
        width: 500,
        height: 322,
        hotspots: [
          {
            id: 1,
            x: 3.8,
            y: 13.4,
            width: 91.6,
            height: 12.4,
            label: 'Abrir Categoria',
            description: 'Clique no campo para ver as opções.',
            evidence: 'observed',
          },
          {
            id: 2,
            x: 4.8,
            y: 27,
            width: 89.6,
            height: 9.3,
            label: 'Pesquisar',
            description: 'Digite uma palavra relacionada ao pedido.',
            evidence: 'observed',
          },
          {
            id: 3,
            x: 4,
            y: 37,
            width: 91.6,
            height: 62.7,
            label: 'Selecionar a opção mais específica',
            description: 'Escolha a opção que melhor representa o caso.',
            evidence: 'guidance',
          },
        ],
      },
    ],
    notes: [
      {
        id: 'urgency-impact',
        text: 'Considere quantas pessoas foram afetadas e se existe uma alternativa.',
        evidence: 'guidance',
      },
      {
        id: 'additional-fields',
        text: 'Campos adicionais podem aparecer conforme seu perfil. Preencha somente quando houver uma opção aplicável ao seu caso.',
        evidence: 'guidance',
      },
    ],
  },
  {
    id: 'describe-and-attach',
    shortTitle: 'Descrever',
    title: 'Descreva o problema e anexe evidências',
    description: 'Explique o ocorrido e anexe somente arquivos úteis.',
    captures: [
      {
        id: 'description-and-attachments',
        title: 'Título, descrição e anexo',
        description: 'Preencha os campos destacados antes de revisar.',
        src: '/portal/descricao-anexos.png',
        width: 980,
        height: 565,
        hotspots: [
          {
            id: 1,
            x: 3,
            y: 7,
            width: 94,
            height: 7,
            label: 'Escrever o título',
            description: 'Resuma o sistema ou equipamento e o problema.',
            evidence: 'observed',
          },
          {
            id: 2,
            x: 3,
            y: 31,
            width: 94,
            height: 18,
            label: 'Descrever o problema',
            description: 'Explique o ocorrido de forma objetiva.',
            evidence: 'observed',
          },
          {
            id: 3,
            x: 31,
            y: 68,
            width: 37,
            height: 9,
            label: 'Anexar evidências',
            description: 'Adicione arquivos úteis de até 2 MB.',
            evidence: 'observed',
          },
        ],
      },
    ],
    checklist: {
      title: 'Na descrição, informe',
      items: [
        'O que aconteceu',
        'Onde ocorreu',
        'Quando começou',
        'Mensagem de erro',
        'O que já tentou',
      ],
      evidence: 'guidance',
    },
    notes: [
      {
        id: 'attachment-privacy',
        text: 'Remova senhas, dados pessoais e informações confidenciais dos anexos.',
        evidence: 'guidance',
      },
    ],
  },
  {
    id: 'review-and-submit',
    shortTitle: 'Revisar',
    title: 'Revise e envie',
    description: 'Confira as informações antes de clicar em Enviar.',
    captures: [
      {
        id: 'review-and-submit-form',
        title: 'Revisão final',
        description: 'Verifique título, descrição e anexos.',
        src: '/portal/descricao-anexos.png',
        width: 980,
        height: 565,
        hotspots: [
          {
            id: 1,
            x: 3,
            y: 7,
            width: 94,
            height: 70,
            label: 'Revisar os campos',
            description:
              'Corrija informações incompletas e remova dados confidenciais.',
            evidence: 'guidance',
          },
          {
            id: 2,
            x: 89,
            y: 88,
            width: 10,
            height: 7,
            label: 'Enviar',
            description: 'Clique somente depois de conferir o formulário.',
            evidence: 'observed',
          },
        ],
      },
    ],
  },
  {
    id: 'track-ticket',
    shortTitle: 'Acompanhar',
    title: 'Acompanhe o chamado',
    description: 'Use filtros e ordenação para localizar o atendimento.',
    captures: [
      {
        id: 'ticket-list',
        title: 'Lista de chamados',
        description: 'Confira os filtros quando um chamado não aparecer.',
        src: '/portal/chamados.png',
        width: 1300,
        height: 420,
        hotspots: [
          {
            id: 1,
            x: 4,
            y: 4,
            width: 12,
            height: 7,
            label: 'Filtrar por status',
            description: 'Revise o filtro aplicado à lista.',
            evidence: 'observed',
          },
          {
            id: 2,
            x: 17,
            y: 4,
            width: 18,
            height: 7,
            label: 'Ordenar por atualização',
            description: 'Veja primeiro os chamados mais recentes.',
            evidence: 'observed',
          },
          {
            id: 3,
            x: 1,
            y: 14,
            width: 97,
            height: 14,
            label: 'Conferir os resultados',
            description:
              'A mensagem indica que o filtro atual não encontrou itens.',
            evidence: 'observed',
          },
        ],
      },
    ],
    notes: [
      {
        id: 'ticket-detail-guidance',
        text: 'Quando houver um chamado, abra-o para acompanhar atualizações.',
        evidence: 'guidance',
      },
    ],
  },
] as const satisfies readonly TutorialStep[];

export type SupportTutorialStep = (typeof supportTutorialSteps)[number];
export type SupportTutorialStepId = SupportTutorialStep['id'];
